### PR TITLE
1/19 Progress notes

### LINKED ISSUE #11: Meeting notes 1-19
Meeting/Progress notes

### PR DESCRIPTION
**Pull request by Amertz08**
Add any work that you did

Resolves #11

### CODE REVIEW

**Comment by Amertz08** [comment]
Do we want to have each section be the progress from lab day to lab day? Or how do we want to segment that?

**Comment by Amertz08** [comment]
We should have issues that aren't code related also tracked w/ github so they are documented.

**Comment by Amertz08** [comment]
For example "ordered parts" which has a finite work product and isn't vague/ambiguous like "researched X". You can mention that as something you did/doing but should not be a full blown issue.

**Comment by Amertz08** [comment]
On the Gantt chart can we export that as an image/PDF? That way we can have it in the repo

**Comment by cduddy** [comment]
So we just need to write what we accomplished today? And what we're planning to do for the future/next week?

**Comment by Amertz08** [comment]
Accomplished since last lab. And make note of future plans yes.

**Comment by cduddy** [comment]
Do we do it here? Or on the issue?

**Comment by Amertz08** [comment]
Pull the branch to your local machine, add changes, commit and push.

**Comment by Amertz08** [comment]
Needs approval. LGTM

**Comment by Amertz08** [comment]
Next time I'll wait for all 3 approvals

**Pull request merged**
