### PR TITLE
2/2 Weekly update

### PR DESCRIPTION
**Pull request by Amertz08**

### CODE REVIEW

**Comment by cduddy** [comment]
My only comment is that Nick has nothing under WIP. Other than that it's good.

**Comment by nBukaty** [comment]
Nothing specific is currently in progress.

**Comment by Amertz08** [comment]
Can someone approve?

**Comment by Amertz08** [comment]
Nick did you mean to put those issues on one line?

**Comment by Amertz08** [comment]
Nvm Nick that makes sense

**Pull request merged**
